<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProvincesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('provinces', function (Blueprint $table) {
            $table->string('id');
            $table->string('name');
            $table->string('departament_id');
            $table->timestamps();
        });
        DB::table('provinces')->insert([
            ['id' => '0101','name' => 'Chachapoyas','departament_id' => '01'],
  ['id' => '0102','name' => 'Bagua','departament_id' => '01'],
  ['id' => '0103','name' => 'Bongará','departament_id' => '01'],
  ['id' => '0104','name' => 'Condorcanqui','departament_id' => '01'],
  ['id' => '0105','name' => 'Luya','departament_id' => '01'],
  ['id' => '0106','name' => 'Rodríguez de Mendoza','departament_id' => '01'],
  ['id' => '0107','name' => 'Utcubamba','departament_id' => '01'],
  ['id' => '0201','name' => 'Huaraz','departament_id' => '02'],
  ['id' => '0202','name' => 'Aija','departament_id' => '02'],
  ['id' => '0203','name' => 'Antonio Raymondi','departament_id' => '02'],
  ['id' => '0204','name' => 'Asunción','departament_id' => '02'],
  ['id' => '0205','name' => 'Bolognesi','departament_id' => '02'],
  ['id' => '0206','name' => 'Carhuaz','departament_id' => '02'],
  ['id' => '0207','name' => 'Carlos Fermín Fitzcarrald','departament_id' => '02'],
  ['id' => '0208','name' => 'Casma','departament_id' => '02'],
  ['id' => '0209','name' => 'Corongo','departament_id' => '02'],
  ['id' => '0210','name' => 'Huari','departament_id' => '02'],
  ['id' => '0211','name' => 'Huarmey','departament_id' => '02'],
  ['id' => '0212','name' => 'Huaylas','departament_id' => '02'],
  ['id' => '0213','name' => 'Mariscal Luzuriaga','departament_id' => '02'],
  ['id' => '0214','name' => 'Ocros','departament_id' => '02'],
  ['id' => '0215','name' => 'Pallasca','departament_id' => '02'],
  ['id' => '0216','name' => 'Pomabamba','departament_id' => '02'],
  ['id' => '0217','name' => 'Recuay','departament_id' => '02'],
  ['id' => '0218','name' => 'Santa','departament_id' => '02'],
  ['id' => '0219','name' => 'Sihuas','departament_id' => '02'],
  ['id' => '0220','name' => 'Yungay','departament_id' => '02'],
  ['id' => '0301','name' => 'Abancay','departament_id' => '03'],
  ['id' => '0302','name' => 'Andahuaylas','departament_id' => '03'],
  ['id' => '0303','name' => 'Antabamba','departament_id' => '03'],
  ['id' => '0304','name' => 'Aymaraes','departament_id' => '03'],
  ['id' => '0305','name' => 'Cotabambas','departament_id' => '03'],
  ['id' => '0306','name' => 'Chincheros','departament_id' => '03'],
  ['id' => '0307','name' => 'Grau','departament_id' => '03'],
  ['id' => '0401','name' => 'Arequipa','departament_id' => '04'],
  ['id' => '0402','name' => 'Camaná','departament_id' => '04'],
  ['id' => '0403','name' => 'Caravelí','departament_id' => '04'],
  ['id' => '0404','name' => 'Castilla','departament_id' => '04'],
  ['id' => '0405','name' => 'Caylloma','departament_id' => '04'],
  ['id' => '0406','name' => 'Condesuyos','departament_id' => '04'],
  ['id' => '0407','name' => 'Islay','departament_id' => '04'],
  ['id' => '0408','name' => 'La Uniòn','departament_id' => '04'],
  ['id' => '0501','name' => 'Huamanga','departament_id' => '05'],
  ['id' => '0502','name' => 'Cangallo','departament_id' => '05'],
  ['id' => '0503','name' => 'Huanca Sancos','departament_id' => '05'],
  ['id' => '0504','name' => 'Huanta','departament_id' => '05'],
  ['id' => '0505','name' => 'La Mar','departament_id' => '05'],
  ['id' => '0506','name' => 'Lucanas','departament_id' => '05'],
  ['id' => '0507','name' => 'Parinacochas','departament_id' => '05'],
  ['id' => '0508','name' => 'Pàucar del Sara Sara','departament_id' => '05'],
  ['id' => '0509','name' => 'Sucre','departament_id' => '05'],
  ['id' => '0510','name' => 'Víctor Fajardo','departament_id' => '05'],
  ['id' => '0511','name' => 'Vilcas Huamán','departament_id' => '05'],
  ['id' => '0601','name' => 'Cajamarca','departament_id' => '06'],
  ['id' => '0602','name' => 'Cajabamba','departament_id' => '06'],
  ['id' => '0603','name' => 'Celendín','departament_id' => '06'],
  ['id' => '0604','name' => 'Chota','departament_id' => '06'],
  ['id' => '0605','name' => 'Contumazá','departament_id' => '06'],
  ['id' => '0606','name' => 'Cutervo','departament_id' => '06'],
  ['id' => '0607','name' => 'Hualgayoc','departament_id' => '06'],
  ['id' => '0608','name' => 'Jaén','departament_id' => '06'],
  ['id' => '0609','name' => 'San Ignacio','departament_id' => '06'],
  ['id' => '0610','name' => 'San Marcos','departament_id' => '06'],
  ['id' => '0611','name' => 'San Miguel','departament_id' => '06'],
  ['id' => '0612','name' => 'San Pablo','departament_id' => '06'],
  ['id' => '0613','name' => 'Santa Cruz','departament_id' => '06'],
  ['id' => '0701','name' => 'Prov. Const. del Callao','departament_id' => '07'],
  ['id' => '0801','name' => 'Cusco','departament_id' => '08'],
  ['id' => '0802','name' => 'Acomayo','departament_id' => '08'],
  ['id' => '0803','name' => 'Anta','departament_id' => '08'],
  ['id' => '0804','name' => 'Calca','departament_id' => '08'],
  ['id' => '0805','name' => 'Canas','departament_id' => '08'],
  ['id' => '0806','name' => 'Canchis','departament_id' => '08'],
  ['id' => '0807','name' => 'Chumbivilcas','departament_id' => '08'],
  ['id' => '0808','name' => 'Espinar','departament_id' => '08'],
  ['id' => '0809','name' => 'La Convención','departament_id' => '08'],
  ['id' => '0810','name' => 'Paruro','departament_id' => '08'],
  ['id' => '0811','name' => 'Paucartambo','departament_id' => '08'],
  ['id' => '0812','name' => 'Quispicanchi','departament_id' => '08'],
  ['id' => '0813','name' => 'Urubamba','departament_id' => '08'],
  ['id' => '0901','name' => 'Huancavelica','departament_id' => '09'],
  ['id' => '0902','name' => 'Acobamba','departament_id' => '09'],
  ['id' => '0903','name' => 'Angaraes','departament_id' => '09'],
  ['id' => '0904','name' => 'Castrovirreyna','departament_id' => '09'],
  ['id' => '0905','name' => 'Churcampa','departament_id' => '09'],
  ['id' => '0906','name' => 'Huaytará','departament_id' => '09'],
  ['id' => '0907','name' => 'Tayacaja','departament_id' => '09'],
  ['id' => '1001','name' => 'Huánuco','departament_id' => '10'],
  ['id' => '1002','name' => 'Ambo','departament_id' => '10'],
  ['id' => '1003','name' => 'Dos de Mayo','departament_id' => '10'],
  ['id' => '1004','name' => 'Huacaybamba','departament_id' => '10'],
  ['id' => '1005','name' => 'Huamalíes','departament_id' => '10'],
  ['id' => '1006','name' => 'Leoncio Prado','departament_id' => '10'],
  ['id' => '1007','name' => 'Marañón','departament_id' => '10'],
  ['id' => '1008','name' => 'Pachitea','departament_id' => '10'],
  ['id' => '1009','name' => 'Puerto Inca','departament_id' => '10'],
  ['id' => '1010','name' => 'Lauricocha ','departament_id' => '10'],
  ['id' => '1011','name' => 'Yarowilca ','departament_id' => '10'],
  ['id' => '1101','name' => 'Ica ','departament_id' => '11'],
  ['id' => '1102','name' => 'Chincha ','departament_id' => '11'],
  ['id' => '1103','name' => 'Nasca ','departament_id' => '11'],
  ['id' => '1104','name' => 'Palpa ','departament_id' => '11'],
  ['id' => '1105','name' => 'Pisco ','departament_id' => '11'],
  ['id' => '1201','name' => 'Huancayo ','departament_id' => '12'],
  ['id' => '1202','name' => 'Concepción ','departament_id' => '12'],
  ['id' => '1203','name' => 'Chanchamayo ','departament_id' => '12'],
  ['id' => '1204','name' => 'Jauja ','departament_id' => '12'],
  ['id' => '1205','name' => 'Junín ','departament_id' => '12'],
  ['id' => '1206','name' => 'Satipo ','departament_id' => '12'],
  ['id' => '1207','name' => 'Tarma ','departament_id' => '12'],
  ['id' => '1208','name' => 'Yauli ','departament_id' => '12'],
  ['id' => '1209','name' => 'Chupaca ','departament_id' => '12'],
  ['id' => '1301','name' => 'Trujillo ','departament_id' => '13'],
  ['id' => '1302','name' => 'Ascope ','departament_id' => '13'],
  ['id' => '1303','name' => 'Bolívar ','departament_id' => '13'],
  ['id' => '1304','name' => 'Chepén ','departament_id' => '13'],
  ['id' => '1305','name' => 'Julcán ','departament_id' => '13'],
  ['id' => '1306','name' => 'Otuzco ','departament_id' => '13'],
  ['id' => '1307','name' => 'Pacasmayo ','departament_id' => '13'],
  ['id' => '1308','name' => 'Pataz ','departament_id' => '13'],
  ['id' => '1309','name' => 'Sánchez Carrión ','departament_id' => '13'],
  ['id' => '1310','name' => 'Santiago de Chuco ','departament_id' => '13'],
  ['id' => '1311','name' => 'Gran Chimú ','departament_id' => '13'],
  ['id' => '1312','name' => 'Virú ','departament_id' => '13'],
  ['id' => '1401','name' => 'Chiclayo ','departament_id' => '14'],
  ['id' => '1402','name' => 'Ferreñafe ','departament_id' => '14'],
  ['id' => '1403','name' => 'Lambayeque ','departament_id' => '14'],
  ['id' => '1501','name' => 'Lima ','departament_id' => '15'],
  ['id' => '1502','name' => 'Barranca ','departament_id' => '15'],
  ['id' => '1503','name' => 'Cajatambo ','departament_id' => '15'],
  ['id' => '1504','name' => 'Canta ','departament_id' => '15'],
  ['id' => '1505','name' => 'Cañete ','departament_id' => '15'],
  ['id' => '1506','name' => 'Huaral ','departament_id' => '15'],
  ['id' => '1507','name' => 'Huarochirí ','departament_id' => '15'],
  ['id' => '1508','name' => 'Huaura ','departament_id' => '15'],
  ['id' => '1509','name' => 'Oyón ','departament_id' => '15'],
  ['id' => '1510','name' => 'Yauyos ','departament_id' => '15'],
  ['id' => '1601','name' => 'Maynas ','departament_id' => '16'],
  ['id' => '1602','name' => 'Alto Amazonas ','departament_id' => '16'],
  ['id' => '1603','name' => 'Loreto ','departament_id' => '16'],
  ['id' => '1604','name' => 'Mariscal Ramón Castilla ','departament_id' => '16'],
  ['id' => '1605','name' => 'Requena ','departament_id' => '16'],
  ['id' => '1606','name' => 'Ucayali ','departament_id' => '16'],
  ['id' => '1607','name' => 'Datem del Marañón ','departament_id' => '16'],
  ['id' => '1608','name' => 'Putumayo','departament_id' => '16'],
  ['id' => '1701','name' => 'Tambopata ','departament_id' => '17'],
  ['id' => '1702','name' => 'Manu ','departament_id' => '17'],
  ['id' => '1703','name' => 'Tahuamanu ','departament_id' => '17'],
  ['id' => '1801','name' => 'Mariscal Nieto ','departament_id' => '18'],
  ['id' => '1802','name' => 'General Sánchez Cerro ','departament_id' => '18'],
  ['id' => '1803','name' => 'Ilo ','departament_id' => '18'],
  ['id' => '1901','name' => 'Pasco ','departament_id' => '19'],
  ['id' => '1902','name' => 'Daniel Alcides Carrión ','departament_id' => '19'],
  ['id' => '1903','name' => 'Oxapampa ','departament_id' => '19'],
  ['id' => '2001','name' => 'Piura ','departament_id' => '20'],
  ['id' => '2002','name' => 'Ayabaca ','departament_id' => '20'],
  ['id' => '2003','name' => 'Huancabamba ','departament_id' => '20'],
  ['id' => '2004','name' => 'Morropón ','departament_id' => '20'],
  ['id' => '2005','name' => 'Paita ','departament_id' => '20'],
  ['id' => '2006','name' => 'Sullana ','departament_id' => '20'],
  ['id' => '2007','name' => 'Talara ','departament_id' => '20'],
  ['id' => '2008','name' => 'Sechura ','departament_id' => '20'],
  ['id' => '2101','name' => 'Puno ','departament_id' => '21'],
  ['id' => '2102','name' => 'Azángaro ','departament_id' => '21'],
  ['id' => '2103','name' => 'Carabaya ','departament_id' => '21'],
  ['id' => '2104','name' => 'Chucuito ','departament_id' => '21'],
  ['id' => '2105','name' => 'El Collao ','departament_id' => '21'],
  ['id' => '2106','name' => 'Huancané ','departament_id' => '21'],
  ['id' => '2107','name' => 'Lampa ','departament_id' => '21'],
  ['id' => '2108','name' => 'Melgar ','departament_id' => '21'],
  ['id' => '2109','name' => 'Moho ','departament_id' => '21'],
  ['id' => '2110','name' => 'San Antonio de Putina ','departament_id' => '21'],
  ['id' => '2111','name' => 'San Román ','departament_id' => '21'],
  ['id' => '2112','name' => 'Sandia ','departament_id' => '21'],
  ['id' => '2113','name' => 'Yunguyo ','departament_id' => '21'],
  ['id' => '2201','name' => 'Moyobamba ','departament_id' => '22'],
  ['id' => '2202','name' => 'Bellavista ','departament_id' => '22'],
  ['id' => '2203','name' => 'El Dorado ','departament_id' => '22'],
  ['id' => '2204','name' => 'Huallaga ','departament_id' => '22'],
  ['id' => '2205','name' => 'Lamas ','departament_id' => '22'],
  ['id' => '2206','name' => 'Mariscal Cáceres ','departament_id' => '22'],
  ['id' => '2207','name' => 'Picota ','departament_id' => '22'],
  ['id' => '2208','name' => 'Rioja ','departament_id' => '22'],
  ['id' => '2209','name' => 'San Martín ','departament_id' => '22'],
  ['id' => '2210','name' => 'Tocache ','departament_id' => '22'],
  ['id' => '2301','name' => 'Tacna ','departament_id' => '23'],
  ['id' => '2302','name' => 'Candarave ','departament_id' => '23'],
  ['id' => '2303','name' => 'Jorge Basadre ','departament_id' => '23'],
  ['id' => '2304','name' => 'Tarata ','departament_id' => '23'],
  ['id' => '2401','name' => 'Tumbes ','departament_id' => '24'],
  ['id' => '2402','name' => 'Contralmirante Villar ','departament_id' => '24'],
  ['id' => '2403','name' => 'Zarumilla ','departament_id' => '24'],
  ['id' => '2501','name' => 'Coronel Portillo ','departament_id' => '25'],
  ['id' => '2502','name' => 'Atalaya ','departament_id' => '25'],
  ['id' => '2503','name' => 'Padre Abad ','departament_id' => '25'],
  ['id' => '2504','name' => 'Purús','departament_id' => '25'],
        ]);

        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('provinces');
    }
}
