(function (window) {
  window.__env = window.__env || {};
  //window.__env.API_DBU = "http://localhost:8000";
  window.__env.API_DBU = "https://bienestar.unas.edu.pe/backend";
  //window.__env.API_DBU = "https://php.dev-bienestar-universitario-unas.site";
  //window.__env.API_GO = "https://api-bienestar.unas.edu.pe";
  window.__env.API_GO = "https://api.dev-bienestar-universitario-unas.site";

  //window.__env.API_GO = "http://127.0.0.1:4021";
  // window.__env.API_DBU = "https://bienestar.unas.edu.pe/backend";
  //window.__env.API_CAJA = "https://tesoreria.unas.edu.pe";
  window.__env.URL_FROND = "https://bienestar.unas.edu.pe";
  //window.__env.URL_FROND = "https://www.dev-bienestar-universitario-unas.site";
  window.__env.ROLE_PSICOPEDAGOGIA = 4;

  window.__env.SECTIONS_REQUIREMENTS_ONE = [
    {
      nombre: "photo-profile",
      descripcion: "Foto Perfil",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 2,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Código estudiante",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "DNI",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Nombres",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Apellidos",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Sexo",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: "M|F",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Dirección Actual",
      descripcion: 'Ejem: Residencia UNAS Britanico N°5',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Fecha de nacimiento",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'date',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Edad",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Correo institucional",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Correo personal",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "celular de estudiante",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'number',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Celular padre",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'number',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Facultad",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Escuela profesional",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Modalidad de ingreso",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Tipo de estudiante",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: "Estudiante|Practicante|Tesista",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    }
  ];

  window.__env.SECTIONS_REQUIREMENTS_TWO = [
    {
      nombre: "Departamento de nacimiento",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'department',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Provincia de nacimiento",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'province',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: true,
      field_dependent: 'Departamento de nacimiento',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Distrito de nacimiento",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'district',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: true,
      field_dependent: 'Provincia de nacimiento',
      value_dependent: '',
      show_dependent: false,
    }
  ];

  window.__env.SECTIONS_REQUIREMENTS_THREE = [
    {
      nombre: "Departamento de procedencia",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'department',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Provincia de procedencia",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'province',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: true,
      field_dependent: 'Departamento de procedencia',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Distrito de procedencia",
      descripcion: '',
      url_guia: '',
      url_plantilla: '',
      opciones: 'district',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: true,
      field_dependent: 'Provincia de procedencia',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Lugar de procedencia exacta",
      descripcion: 'Ejem: Brisas del Hualla comité 7, Calle las gardenias Mz F lt 10 -  Frente a la pollería ZZZ',
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'red',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Croquis o foto de su vivienda",
      descripcion: "Llenar el formato de acuerdo a la guia",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 2,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
  ];

  window.__env.SECTIONS_REQUIREMENTS_FOURTH = [
    {
      nombre: "¿Postula por primera vez a los servicios por medio de esta plataforma web?",
      descripcion: "",
      url_guia: '',
      url_plantilla: '',
      opciones: 'Si|No',
      tipo_requisito_id: 5,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Copia de DNI de los padres",
      descripcion: "Subir documento con los DNI de los padres escaneados",
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: '¿Postula por primera vez a los servicios por medio de esta plataforma web?',
      value_dependent: 'Si',
      show_dependent: true,
    },
    {
      nombre: "¿Es usted victima de terrorismo?",
      descripcion: "",
      url_guia: '',
      url_plantilla: '',
      opciones: 'Si|No',
      tipo_requisito_id: 5,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Resolución de víctima de terrorismo (Otorgado por Consejo Universitario)",
      descripcion: "En caso de ser victima de terrorismo",
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: '¿Es usted victima de terrorismo?',
      value_dependent: 'Si',
      show_dependent: true,
    },
    {
      nombre: "¿Usted es menor de edad?",
      descripcion: "",
      url_guia: '',
      url_plantilla: '',
      opciones: 'Si|No',
      tipo_requisito_id: 5,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Carta de compromiso de los padres para uso de los servicios solicitados (Menores de edad)",
      descripcion: "Llenar el formato de acuerdo a la guia",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_PLANTILLA_CARTA_COMPROMISO_PADRES.docx",
      url_plantilla: '',
      opciones: '¿Usted es menor de edad?',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: '¿Usted es menor de edad?',
      value_dependent: 'Si',
      show_dependent: true,
    },
    {
      nombre: "Solicitud dirigida a la dirección de bienestar universitario",
      descripcion: "Adquirir en caja - UNAS",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_SOLICITUD_DIRIGIDA_DBU.pdf",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    /*,
    {
      nombre: "Reporte de deudas de tesoreria / Ingresantes constancia de matricula)",
      descripcion: "Solicitar en caja ubicada en pabellon central caja - UNAS / Solicitar en Dirección de Asuntos Academicos DIAA",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_REPORTE_DEUDA.jpg",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true
    },
    ,*/

    {
      nombre: "Carta de practicante",
      descripcion: "Llenar el formato de acuerdo a la guia",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: 'Tipo de estudiante',
      value_dependent: 'Practicante',
      show_dependent: true,
    },
    {
      nombre: "Resolución de tesista",
      descripcion: "Llenar el formato de acuerdo a la guia",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: 'Tipo de estudiante',
      value_dependent: 'Tesista',
      show_dependent: true,
    }
  ];

  window.__env.SECTIONS_REQUIREMENTS_FIVE = [
    /*{
      nombre: "Ficha socioeconómica",
      descripcion: "Subir una captura de la ficha socioeconómica actualizada (servicio social y pag web)",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_FICHA_SOCIECONOMICA_UNAS_2024.pdf",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false
    },/*
    /*
    {
      nombre: "Un (01) fotografia actualizada",
      descripcion: "Tamaño carnet y/o pasaporte",
      url_guia:
        "https://academico.unas.edu.pe/resources/Photos/Students/2021/UNAS002018061774761761.jpg",
      url_plantilla: "",
      opciones: "",
      tipo_requisito_id: 2,
      activo: true,
    },
    */
    {
      nombre: "SISFOH (Clasificación socioeconómica) vigente",
      descripcion: "Subir el documento generado por la pagina web de SISFOH en la siguiente guia",
      url_guia: "https://operaciones.sisfoh.gob.pe:450/cse/",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Clasificación según su SISFOH vigente",
      descripcion: "Ingrese su clasificación de acuerdo a su SISFOH",
      url_guia: '',
      url_plantilla: '',
      opciones: "POBRE EXTREMO|POBRE|NO POBRE|NO REGISTRA",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    /*
    {
      nombre: "Certificado domiciliario",
      descripcion: "Certificado firmado por alguna autoridad de tu lugar de procedencia",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_CERTIFICADO_DOMICILIARIO.png",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true
    },
    */
    {
      nombre: "Copia de recibo de luz y/o agua",
      descripcion: "En caso de no contar con recibo, subir documento que lo acredite",
      url_guia: '',
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Copia de DNI del solicitante",
      descripcion: "Subir documento con los DNI del solicitante escaneado",
      url_guia: '',
      url_plantilla: '',
      opciones: '¿Postula por primera vez a los servicios por medio de esta plataforma web?',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: true,
      field_dependent: '¿Postula por primera vez a los servicios por medio de esta plataforma web?',
      value_dependent: 'Si',
      show_dependent: true,
    },
    {
      nombre: "¿Quién o quiénes aportan económicamente en tu hogar?",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Papá|Mamá|Hermanos|Estudiante|Otros',
      tipo_requisito_id: 6,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "¿Cuánto es el ingreso económico mensual de tu hogar?",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'number',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
  ];

  window.__env.SECTIONS_REQUIREMENTS_SIX = [
    {
      nombre: "Seguro de salud",
      descripcion: "Seleccionar su tipo de seguro",
      url_guia: '',
      url_plantilla: '',
      opciones: "SIS|EsSalud|Otro seguro",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Constancia vigente (SIS, EsSalud, Otro)",
      descripcion: "Subir imagen de seguro vigente, puede obtener la información en la siguiente guia",
      url_guia: "http://app.sis.gob.pe/SisConsultaEnLinea/Consulta/frmConsultaEnLinea.aspx",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Carnet de vacuna antitetanica",
      descripcion: "subir fotografia del carnet de vacunación",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Carnet de vacuna antihepatitis",
      descripcion: "subir fotografia del carnet de vacunación",
      url_guia: "",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Formato de atención de los servicios de DBU",
      descripcion: "Tener los sello de odontología, psicopedagogía y centro médico.",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_CONTANCIA_EVALUACION.jpg",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "CONSTANCIA DE ASISTENCIA A LOS TALLERES DE DBU 2024-I SELLADO POR PSICOPEDAGOGÍA (MÍNIMO 01 TALLER) O CARTA COMPROMISO",
      descripcion: "Llenar el formato de acuerdo a la guia",
      url_guia: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_PLANTILLA_CARTA_COMPROMISO_ASISTECIA_TALLERES.pdf",
      url_plantilla: '',
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    }
  ];

  window.__env.SECTIONS_REQUIREMENTS_SEVEN = [
    {
      nombre: "Certificado único laboral actualizado CERTIJOVEN (Pag web del Ministerio de Trabajo)",
      descripcion: "Subir el documento generano por la pagina web para obtener su CERTIJOVEN en la siguiente guia",
      url_guia: "https://www.empleosperu.gob.pe/portal-mtpe/#/nuevo-usuario",
      url_plantilla: "https://bienestar.unas.edu.pe/backend/storage/app/guias/1_GUIA_CERTIJOVEN.pdf",
      opciones: '',
      tipo_requisito_id: 1,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Certijoven policiales",
      descripcion: "Antecedentes policiales",
      url_guia: '',
      url_plantilla: '',
      opciones: "No tiene|Si tiene",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Certijoven judiciales",
      descripcion: "Antecedentes judiciales",
      url_guia: '',
      url_plantilla: '',
      opciones: "No tiene|Si tiene",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Certijoven penales",
      descripcion: "Antecedentes penales",
      url_guia: '',
      url_plantilla: '',
      opciones: "No tiene|Si tiene",
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: false,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    }
  ];

  window.__env.SECTIONS_FAMILY_COMPOSITION  = [
    {
      nombre: "Nombres y apellidos",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Edad",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'number',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Estado civil",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Soltero|Casado|Viudo',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Parentesco",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Padre|Madre|Hermano|Abuelos|Primos',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Nivel educativo",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Primaria|Secundaria|Superior',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Ocupación",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: '',
      tipo_requisito_id: 3,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
  ];

  window.__env.SECTIONS_DWELLING  = [
    {
      nombre: "Tenencia Hogar",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Propia|Hipotecada|Alquilada|Alojado|Guardiania|Invación',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Pared",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Noble|Adobe|Madera|Quincha|Esteras|Otros',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Piso",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Tierra|Parquet|Cerámica|Concreto|Cemento|Otros',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Techo",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Calamina|Esteras|Paja|Madera|Plásticos|Otros',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Zona de la Vivienda",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Urbana|Rural|Residencial|AA.HH|Otros',
      tipo_requisito_id: 4,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "¿Tiene moto lineal?",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Si|No',
      tipo_requisito_id: 5,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "Equipamiento de la Vivienda",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Equipo de sonido|Refrigeradora o Congeladora|Televisor|Cocina a Gas|Licuadora|Lavadora|Computadora|Horno Microondas',
      tipo_requisito_id: 6,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
    {
      nombre: "¿Con qué servicios cuentas?",
      descripcion: "",
      url_guia: "",
      url_plantilla: "",
      opciones: 'Agua potable|Desagüe|Energía eléctrica|Internet|Cable|Otros',
      tipo_requisito_id: 6,
      activo: true,
      type_input: 'text',
      text_color: 'default',
      text_type: 'normal',
      text_size: 'md',
      is_recoverable: true,
      is_dependent: false,
      field_dependent: '',
      value_dependent: '',
      show_dependent: false,
    },
  ];

  window.__env.GOOGLE_RECAPTCHA_SITEKEY = "6LeHadskAAAAADv1LgwVU2Xe9sOQqiRt2Sfkr-5-";

  window.__env.enableDebug = true;
})(this);
